### ISSUE TITLE
Consider changing region in helm values to westus

### ISSUE THREAD

**Issue by rossf7** [Azure/kubernetes-carbon-intensity-exporter#23]
Hi @helayoty @Fei-Guo,
first of all thanks for creating this project! 💚 I've been interested in carbon aware scaling for a while so I was excited to see this project.

I hit an error installing the exporter in kind when using `eastus` as the region in the helm values.

```
fail: CarbonAware.DataSources.WattTime.Client.WattTimeClient[0]
      Error getting data from WattTime.  StatusCode: Forbidden. Response: StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        Date: Fri, 19 May 2023 10:23:29 GMT
        Transfer-Encoding: chunked
        Connection: keep-alive
        Server: nginx
        Content-Type: application/json
      }
fail: CarbonAware.WebApi.Filters.HttpResponseExceptionFilter[0]
      Exception: Error requesting forecast?ba=PJM_ROANOKE
```

Changing the region to `westus` prevents the error because it maps to the `CAISO_NORTH` balancing authority for which WattTime kindly provide data for free.

Is it worth changing the region in the helm values and docs?

Users would still need a WattTime license to access other regions but they can get started with `westus` without hitting errors. I'm happy to submit a PR if you think this is useful.

**Comment by helayoty** [comment]
@rossf7 , thanks for your feedback. Glad to hear you tried it out. You are welcome to open a PR to address region change.

**Comment by rossf7** [comment]
Hi @helayoty thank you! Here is the PR https://github.com/Azure/kubernetes-carbon-intensity-exporter/pull/25
