### ISSUE TITLE
Add support for Electricitymaps

### ISSUE THREAD

**Issue by tkennes** [Azure/kubernetes-carbon-intensity-exporter#27]
Hi there,

I recently heard about this project here: https://rossfairbanks.com/2023/06/05/carbon-aware-temporal-shifting-with-keda/, and first off, amazing initiative, this is exactly what we need, big fan! :) 

Now, would it perhaps be an idea to support Electricitymaps next to Wattime as well? They do seem to boast different numbers, but generally offer a more granular and greater coverage of the world in general. Also, in Europe they are known to be quite accurate.

Let me know, curious to hear your answer! Judging from the current code, we could achieve this by adding a little bit of data wrangling before processing it further as is.

kind regards,
Tom

**Comment by rossf7** [comment]
Thanks @helayoty I've had a go at implementing this by extending the helm chart. PTAL when you have time

https://github.com/Azure/kubernetes-carbon-intensity-exporter/issues/27

**Comment by rossf7** [comment]
@helayoty @pauldotyu Thanks so much for getting this approved and released!

@madsnedergaard You might be interested in this as it means https://github.com/Azure/carbon-aware-keda-operator can be used with Electricity Maps data.

**Comment by madsnedergaard** [comment]
Thanks for pinging, that's very exciting! 🙌
